# Generated by Django 3.0.6 on 2020-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalite',
            name='link_nationalite',
            field=models.CharField(max_length=200),
        ),
    ]
