# Generated by Django 3.0.6 on 2020-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medailles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medaille',
            name='link_medaille',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medaille',
            name='nom_medaille',
            field=models.CharField(max_length=42),
        ),
    ]
