# Generated by Django 3.0.6 on 2020-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='nom_athlete',
            field=models.CharField(max_length=42),
        ),
    ]
