# Generated by Django 3.0.6 on 2020-06-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medailles', '0002_auto_20200604_1211'),
        ('athletes', '0002_auto_20200604_1211'),
        ('epreuves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(max_length=100)),
                ('athlete', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete')),
                ('epreuve', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='epreuves.Epreuve')),
                ('medaille', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='medailles.Medaille')),
            ],
        ),
    ]
